### ISSUE TITLE
error="failed to read transceiver info; libusb: overflow [code -8]"

### ISSUE THREAD

**Issue by bony97** [betom84/kl-logger#1]
Hallo Tom,

ich versuche gerade deinen kl-logger auf meiner pi3 mit raspberryOS (buster) zum laufen zu bringen. 
Mittlerweile habe ich "go" installiert und auch "libusb". Ich konnte auch erfolgreich "go build" laufen lassen, allerdings weiß ich nicht, mit welchen Befehl ich die erstellte "kl-logger" starten kann.
Versuche ich "go run main.go" kommt folgender Fehler

***************************************
go run main.go
INFO[2021-01-30T15:03:57+01:00] log level is set to 'info'
INFO[2021-01-30T15:03:57+01:00] usb transceiver connected                     productID=0x5555 vendorID=0x6666
PANI[2021-01-30T15:03:57+01:00]                                               error="failed to read transceiver info; libusb: overflow [code -8]"
panic: (*logrus.Entry) 0x14581c0

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0x152a180, 0x140c500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/pi/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:255 +0x314
github.com/sirupsen/logrus.(*Entry).Log(0x1458180, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:283 +0x9c
github.com/sirupsen/logrus.(*Entry).Panic(0x1458180, 0x0, 0x0, 0x0)
        /home/pi/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:321 +0x3c
main.main()
        /opt/kl-logger/main.go:59 +0x7c
exit status 2
***************************************

Kannst du mir vielleicht weiter helfen?

Gruß,
Tobias

**Comment by betom84** [comment]
Moin Tobias,

du kannst das mit `go build` erstellte Binary mit `./kl-logger` starten.
Der Fehler würde mich im ersten Moment auf fehlende Zugriffsrechte tippen lassen, probier mal das ganze mit `sudo` bzw. als root auszuführen.

Gruß,
Tom

**Comment by bony97** [comment]
Moin Tom,

 

vielen Dank für deine Antwort und entschuldige bitte die späte Rückmeldung.

Leider habe ich momentan viel um die Ohren und das Projekt liegt damit erstmal auf Eis.

Wenn ich mich wieder ausführlicher damit beschäftigen kann, werde ich der Sache mit den Zugriffsrechten mal auf den Grund gehen.

 

Viele Grüße,

Tobias

 

Gesendet: Samstag, 13. Februar 2021 um 22:57 Uhr
Von: "Tom Beyer" <notifications@github.com>
An: "betom84/kl-logger" <kl-logger@noreply.github.com>
Cc: "bony97" <tobiasneubert@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [betom84/kl-logger] error="failed to read transceiver info; libusb: overflow [code -8]" (#1)


 

Moin Tobias,

du kannst das mit go build erstellte Binary mit ./kl-logger starten.
Der Fehler würde mich im ersten Moment auf fehlende Zugriffsrechte tippen lassen, probier mal das ganze mit sudo bzw. als root auszuführen.

Gruß,
Tom
